### ISSUE TITLE
ConnectedToRelay is registered too late

### ISSUE THREAD

**Issue by bboysil** [Derek-R-S/Light-Reflective-Mirror#1]
Latest change breaks connecting to relay:
     ```
   private void OnEnable()
        {
            clientToServerTransport.OnClientConnected = ConnectedToRelay;
           ...
```

If I have "Connect on Awake" checked then `ConnectToRelay()` is called before `OnEnable()` so `ConnectedToRelay()` is never called and LRMTransport doesn't know it was actually connected(_connectedToRelay remains false).

**Comment by Derek-R-S** [comment]
Been fixed, just forgot to close issue.
