### ISSUE TITLE
ServerId is wrong on LightReflectiveMirrorTransport component

### ISSUE THREAD

**Issue by sableangle** [Derek-R-S/Light-Reflective-Mirror#14]
Use the ver in Release 9.0.
The ServerId on LightReflectiveMirrorTransport component didn't match the value return by the API /api/servers.

For instance, on my Unity host the ServerId value is 19, but the /api/servers return value like this:
`
[
  {
    "serverId": 963094828,
    "hostId": 22,
    "serverName": "Squid_4145's Room",
    "serverData": "Map 1",
    "isPublic": true,
    "maxPlayers": 6,
    "clients": []
  }
]
`

Seems the hostId is fill into the ServerId on host's LightReflectiveMirrorTransport component.

**Comment by sableangle** [comment]
Oh I have read the latest code on main branch, maybe this issue is fixed in new version.
I will try after a new major release is release

**Comment by cxxpxr** [comment]
Fixed in bleeding edge. You can update to that or wait for v10 :)
