### ISSUE TITLE
The ability to use user's Json Library in LRM

### ISSUE THREAD

**Issue by sableangle** [Derek-R-S/Light-Reflective-Mirror#17]
Since there is usually already a Json library is in a Unity project. (But maybe not JSON.Net)
I wish to let user use their Json Library to deserialize json in LRM.

Currently I do some modify like this

Add the delegate in LightReflectiveMirrorTransport
```csharp
public static System.Func<string, List<Room>> OnDeserializeRoom;
public static System.Func<string, RelayAddress> OnDeserializeRelayAddress;
```

Then register the delegate. In my case I use LitJson.

(Some script execute before Transport init)
```csharp
public override void Awake()
{
        LightReflectiveMirror.LightReflectiveMirrorTransport.OnDeserializeRoom += (result) =>
        {
            return LitJson.JsonMapper.ToObject<List<LightReflectiveMirror.Room>>(result);
        };
        
        LightReflectiveMirror.LightReflectiveMirrorTransport.OnDeserializeRelayAddress += (result) =>
        {
            return LitJson.JsonMapper.ToObject<LightReflectiveMirror.RelayAddress>(result);
        };
}
```

I have done this modify in my local branch, if you also think this is a good idea, I will make a pull request.
Or any suggestion about the implementation is welcome.

**Comment by cxxpxr** [comment]
I don't think it's necessary to have support for EVERY json lib, i think we can switch the unity's built in one though

**Comment by sableangle** [comment]
Got it!
I have done a version in #18 which use the Unity's built in JsonUtility as the default serializer. (With a dirty hack in client side, so this may not be the best solution)

But I found a better way to make JsonUtility to support Json Array in https://stackoverflow.com/questions/36239705/serialize-and-deserialize-json-and-json-array-in-unity

If you don't mind, I would like to doing the migration from Json.Net into JsonUtility with the method found in StackOverflow. And will send a new pull request.

**Comment by cxxpxr** [comment]
awesome, if you can do a pr for just that, it would be very appreciated.
