### ISSUE TITLE
AWS connection issues

### ISSUE THREAD

**Issue by SaFrMo** [Derek-R-S/Light-Reflective-Mirror#19]
Absolutely love this asset and the YouTube tutorials, thank you so much for putting them together!

I'm trying to set up an AWS relay server and am not having any luck just yet. I've got LRM installed and running on the EC2 instance without any problem, and I've allowed incoming traffic from ports 7776, 7777, and 8080 on the server. 

While following the [Unity tutorial](https://www.youtube.com/watch?v=Wi0rp2b8KmM), I'm getting a KCP timeout error in Unity after 10 seconds: `KCP: Connection timed out after not receiving any message for 10000ms. Disconnecting.` 

I've tried pasting both the public and private IP addresses of the EC2 instance into the LRM Server IP field with the same result. Can you think of anything I might be missing or if there's something AWS-specific I should be doing?

Thanks again, really appreciate your work on this!

**Comment by cxxpxr** [comment]
Hi, an issue like this will probably require a bit of back and forth so feel free to join our discord and post the issue in our help channel

https://discord.gg/34BPq26XDX

**Comment by SaFrMo** [comment]
Issue solved thanks to derek and sweety on the discord channel! I had allowed TCP connections to ports 7776, 7777, and 8080 on the EC2 instance, but I needed to switch that to allow UDP connections to those same ports instead. Works great now - thanks again, all!
