### ISSUE TITLE
Think about at P2P to get fast dealy and lower bandwith cost?

### ISSUE THREAD

**Issue by orangeagain** [Derek-R-S/Light-Reflective-Mirror#22]
[N2N](https://github.com/ntop/n2n) is good choice to let mirror built-in, what do you guys think about it?

**Comment by cxxpxr** [comment]
This has nothing to do with LRM? Keep discussion in the mirror discord or my own, thanks :)

**Comment by orangeagain** [comment]
> This has nothing to do with LRM? Keep discussion in the mirror discord or my own, thanks :)

So where is discord ?

**Comment by cxxpxr** [comment]
https://discord.gg/9BaQN6Wm

**Comment by adriancabouli** [comment]
Hi where is discord?

**Comment by cxxpxr** [comment]
https://discord.gg/JuJcBjCJYc

**Comment by adriancabouli** [comment]
thanks! i´ve just wrote a message if somebody can help me. thanks!
