### ISSUE TITLE
GET request to http://{loadBalancerAddress}:{loadBalancerPort}/api/join/ returns "Method Not Implemented: Get /api/join"

### ISSUE THREAD

**Issue by Barbarezza** [Derek-R-S/Light-Reflective-Mirror#29]
Hello! I've followed both tutorials and put everything on an EC2 instance on AWS, but nothing seems to be happening. I state that I have a lot of inexperience on the BE side, so I might be doing something wrong.

Nothing seems to happen when I connect to Unity, and doing some Debugging I noticed that this request returns Method Not Implemented. Any idea what I might have been doing wrong?

**Comment by cxxpxr** [comment]
closing as load balancer is deprecated
