### ISSUE TITLE
Dedicated server config

### ISSUE THREAD

**Issue by alfiolocastro** [Derek-R-S/Light-Reflective-Mirror#3]
Hi Derek-R-S,
I have some issues using the server on a remote (linux) machine,
The server dll starts e shows up all the standards messages, it receives client connections as well.

The things gets weird on client side when starting mirror as a host/server and the LRM transport does not receives back the "Server Id" from the relay.

Tried on your machine [34.67.125.123] and on a local network machine and it works as expected (very well btw!)

so... is there any config I should pay attention on for a linux (debian10) server?

**Comment by peterparnes** [comment]
I run the LRM-server on a Ubuntu-20-server without any problems. I just started it with dotnet.

**Comment by alfiolocastro** [comment]
Never mind, a stupid file permission issue.
