### ISSUE TITLE
KCP: Random amounts of lobbies crashing/freezing at random intervals

### ISSUE THREAD

**Issue by VirtualBrightPlayz** [Derek-R-S/Light-Reflective-Mirror#30]
I'm using v12 and one relay server, and the image attached is (likely) outputted to the console when it crashes.
By crash/freeze, I mean the lobby stops sending and receiving traffic. No disconnect packets are sent from what I've gathered, but the relay itself is still functional, but people just need to restart their lobbies.
![unknown](https://user-images.githubusercontent.com/21286339/149179605-4c5e1710-9895-4f6d-a60a-292b31baf32d.png)
I am also using a piece of software called pterodactyl to "host" the web panel for the console, and I'm using AWS Lightsail to host it.
If you need to quickly contact me, my Discord is `Virtual#7802`

EDIT#1:
After looking through the source code of KCP and the relay, it seems it's just an issue with KCP, so I am going to switch the relay to use websockets or something else and see if that fixes it.

**Comment by cxxpxr** [comment]
kcp might have been changed on mirrors side, which could be causing this

**Comment by cxxpxr** [comment]
Make sure KCP is set to nonalloc = false as well

**Comment by VirtualBrightPlayz** [comment]
I'll have to update mirror in our project. For now, I'll close this issue. Thanks!
