### ISSUE TITLE
[Error] Arguments being passed are in the wrong sequence.

### ISSUE THREAD

**Issue by Shark-vil** [Derek-R-S/Light-Reflective-Mirror#32]
https://github.com/Derek-R-S/Light-Reflective-Mirror/blob/25c9891e19b37c69f21638d61cf646c3909a3470/UnityProject/Assets/Mirror/Runtime/Transport/LRM/LRMTransport/LRMTransportDirectConnect.cs#L63

---

![Unity_f1khvRm5R7](https://user-images.githubusercontent.com/13109606/150005553-3d278071-0913-40c3-a6c8-f65dc792e5ae.png)
--

Before:
![devenv_oxO4fzXl3B](https://user-images.githubusercontent.com/13109606/150004869-9f37031a-c67a-4b16-9c3b-b04b77bb4803.png)

After:
![devenv_ssZIRtWmHA](https://user-images.githubusercontent.com/13109606/150004895-ddcca831-545b-4acf-86a0-07acca89f906.png)

**Comment by Shark-vil** [comment]
In fact, these methods appear to be identical. What is compiler splitting for?

**Comment by cxxpxr** [comment]
your mirror defines are messed up. not an LRM bug
