### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by rafaeldolfe** [Derek-R-S/Light-Reflective-Mirror#33]
The read me says it uses the MIT license but I cannot find it in the repo iself. I assume it is missing?

**Comment by Derek-R-S** [comment]
I don't see a need for a license file inside the repo, it's MIT so do whatever you want with the code.

**Comment by Derek-R-S** [comment]
I have added a license file though

**Comment by rafaeldolfe** [comment]
I am deploying LRM to an app owned by a company (in its gitlab repo). Unless there is a license file in this repo, technically the company is not allowed to commercialize the app I believe. I'm not 100% sure on the details but I just want to feel totally legit in using the software. :)

**Comment by Derek-R-S** [comment]
Yup no worries, should be good to go now
