### ISSUE TITLE
When i start a server, it has a player?

### ISSUE THREAD

**Issue by msyzzm** [Derek-R-S/Light-Reflective-Mirror#38]
Why Room.currentPlayers add 1?

`public int currentPlayers { get => clients.Count + 1; } // player count`

**Comment by cxxpxr** [comment]
clients list doesnt include host

**Comment by msyzzm** [comment]
> clients list doesnt include host

But when start a server (not host), it will add 1 too.

**Comment by Derek-R-S** [comment]
LRM was designed with player hosted games in mind, as generally speaking servers wouldnt need a relay. If you wish to use LRM for servers and not include one in the server count, it is pretty easy to modify and is open source.

**Comment by cxxpxr** [comment]
LRM is only designed for player hosted games, if you wanted a dedicated server, you could just host that instead, a relay is redundant
